[package]
name = "Iriax72/jeu-simulation"
version = "0.1.0"
description = "Mon jeu en C# avec Blazor webAssembly"

[[module]]
name = "serveur-statique"
source = "wasmer/static-web-server"

[[commands]]
name = "run"
module = "serveur-statique"
runner = "https://webc.org/wasmer/staticserver"

[fs]
public = "bin/Release/net10.0/browser-wasm/publish/wwwroot"